version: '3.4'

services:
  app:
    build: .
    image: rest-service-app
    working_dir: /src
    volumes:
      - ./:/src
    environment:
      PORT: ${PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always
    networks:
      - rest-net
  postgres:
    build: ./database
    image: rest-service-postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_EXPOSE_PORT}
    volumes:
      - rest-service-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - rest-net
volumes:
  rest-service-data:
networks:
  rest-net:
    driver: bridge
