version: '3.8'

services:
  postgres:
    build: ./database
#    image: rybakn/rest-service-postgres:1
    ports:
      - "5432:5432"
    volumes:
      - rest-service-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
    restart: always
    networks:
      rest-net: {}
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_PASSWORD: "secret"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - rest-net
volumes:
  rest-service-data:
networks:
  rest-net:
    driver: bridge
